### ISSUE TITLE
virtkey can't be found anymore

### ISSUE THREAD

**Issue by lowks** [solos/musca#1]
Virtkey can't be found anymore, thus `pip install -r requirements.txt` will fail.

**Comment by solos** [comment]
virtkey could be found in https://launchpad.net/virtkey

**Comment by lowks** [comment]
Then I guess you should change `requirements.txt` because by default it will only look in `pypi` and fail when cannot find.

**Comment by lowks** [comment]
Try this: https://github.com/solos/musca/pull/2

**Comment by solos** [comment]
:+1:
